[package]
name = "track-rename"
version = "3.0.0"
edition = "2024"
authors = ["Esgrove <esgrove@outlook.com>"]
description = "CLI tool for formatting and renaming audio tracks"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Esgrove/track-rename"
keywords = ["cli", "music", "audio", "rename"]
categories = ["command-line-utilities"]
default-run = "trackrename"
rust-version = "1.98"

[dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
base64 = "0.23.1"
byteorder = "1.5.0"
clap = { version = "4.6.7", features = ["derive"] }
clap_complete = "4.6.11"
colored = "3.1.1"
crossterm = "0.29.0"
difference = "2.0.0"
dirs = "7.0.0"
dunce = "1.0.5"
id3 = { git = "https://github.com/Esgrove/rust-id3/" }
itertools = "0.15.0"
metaflac = "0.2.8"
rand = "0.10.3"
rayon = "1.12.0"
regex = "1.13.1"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
tempfile = "3.27.0"
titlecase = "3.6.0"
toml = "1.1.6"
trash = "5.2.9"
unicode-normalization = "0.1.25"
walkdir = "2.5.0"

[dev-dependencies]
criterion = "0.8.2"

[[bin]]
name = "trackrename"
path = "src/main.rs"

[[bin]]
name = "trackprint"
path = "src/bin/trackprint.rs"

[[bin]]
name = "crateprint"
path = "src/bin/crateprint.rs"

[[bench]]
name = "formatting"
harness = false

[[bench]]
name = "serato"
harness = false

[[bench]]
name = "io"
harness = false

[profile.dev]
incremental = true

[profile.release]
lto = true
# https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
codegen-units = 1

[lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[lints.clippy]
# https://rust-lang.github.io/rust-clippy/master/index.html
fn_params_excessive_bools = "allow"
struct_excessive_bools = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"

cast_possible_wrap = "deny"
char_lit_as_u8 = "deny"
enum_glob_use = "deny"
exit = "deny"
fn_to_numeric_cast = "deny"
fn_to_numeric_cast_with_truncation = "deny"
indexing_slicing = "deny"
panic = "deny"
panic_in_result_fn = "deny"
ptr_as_ptr = "deny"
string_slice = "deny"
unchecked_time_subtraction = "deny"
unimplemented = "deny"
unnecessary_cast = "deny"
unwrap_used = "deny"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
