# Copy config to ~/.config/track-rename.toml

# Convert files that can't be read to AIFF.
# The typical issue is unsupported (old) ID3 tag version format,
# which will be fixed by converting the file.
convert_failed = false

# List of filenames to ignore.
# These can be with the file extension or not.
exclude = []
