name: Python ruff

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/ruff.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/ruff.yml"

# https://github.com/chartboost/ruff-action
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ruff lint
        uses: chartboost/ruff-action@v1
        with:
          args: check --verbose

      - name: Ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check --verbose
